### ISSUE TITLE
[BUG]get concurrent.futures._base.TimeoutError

### ISSUE THREAD

**Issue by rushmj** [truera/trulens#1009]
when I run:
with tru_rag as recording:
    for question in eval_questions:
        response = vector_rag.query(question)

I get "concurrent.futures._base.TimeoutError"

**Comment by joshreini1** [comment]
@rushmj can you share more info including the stack trace and reproducible code example?

**Comment by rushmj** [comment]
Run of run in <Thread(TP.submit with debug timeout_2, started 138842688448064)> timed out after 600.0 second(s).
None
exception calling callback for <Future at 0x7e43a8a7c0a0 state=finished raised TimeoutError>
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "/home/guest/.local/lib/python3.10/site-packages/trulens_eval/app.py", line 1168, in _add_future_feedback
    res = future_result.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/trulens_eval/utils/python.py", line 374, in _future_target_wrapper
    return func(*args, **kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/trulens_eval/utils/threading.py", line 168, in _run_with_timeout
    raise e
  File "/home/guest/.local/lib/python3.10/site-packages/trulens_eval/utils/threading.py", line 159, in _run_with_timeout
    res: T = fut.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by piotrm0** [comment]
Hi @rushmj , can you share how you structured the app you are recording here?

**Comment by joshreini1** [comment]
@rushmj - please let us know if you're still facing this issue. If so, please share your app setup. Closing for now.
