### ISSUE TITLE
[BUG] UnicodeDecodeError: 'gbk' codec can't decode

### ISSUE THREAD

**Issue by liuxiaocs7** [truera/trulens#1010]
**Bug Description**
What happened?

```
Exception in thread Thread-3 (_future_target_wrapper):
Traceback (most recent call last):
  File "D:\Development\Tools\Miniconda3\envs\reasoning\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "D:\Development\Tools\Miniconda3\envs\reasoning\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Development\Tools\Miniconda3\envs\reasoning\Lib\site-packages\trulens_eval\utils\python.py", line 386, in _future_target_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Development\Tools\Miniconda3\envs\reasoning\Lib\site-packages\trulens_eval\tru.py", line 1043, in listen_to_dashboard
    line = pipe.readline()
           ^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 2: illegal multibyte sequence
Tru was already initialized. Cannot change database_url=sqlite:///default.sqlite or database_file=None .
```

**To Reproduce**
Which steps should someone take to run into the same error? A small, reproducible code example is useful here.

**Expected behavior**

**Relevant Logs/Tracebacks**
Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. If the issue is related to the TruLens dashboard, please also include a screenshot.

**Environment:**
 - OS: [e.g. MacOS, Windows]
 - Python Version
 - TruLens version
 - Versions of other relevant installed libraries

**Additional context**

**Comment by joshreini1** [comment]
@liuxiaocs7 please complete the bug description so we can properly diagnose the is issue. Thanks!

**Comment by joshreini1** [comment]
Not enough information here to reproduce/solve. Closing until more information is provided
