### ISSUE TITLE
[BUG] App Freezes after Crash on Another Thread followed by `app.wait_for_feedback_results()`

### ISSUE THREAD

**Issue by cabouezzi** [truera/trulens#1205]
**Bug Description**
Using the vanilla relevance, context relevance, and groundedness feedback functions. Locally run custom app using Ollama as both responder and provider/judge. Firstly, there are errors occurring on separate threads (see traceback). The app doesn't crash, however `app.wait_for_feedback_results()` freezes the program if a thread crashes.

**To Reproduce**
Purposely crash one of the threads to see the freezing behavior. For the exact TimeOutError, perhaps use a large LLM that will take >10 minutes for responding. (Reasoning being it will occasionally say timed out after 600s, unable to reproduce however.)

**Expected behavior**

**Relevant Logs/Tracebacks**
```
Traceback (most recent call last):
  File "/Path/MyProject/compare.py", line 30, in <module>
  File "/Path/MyProject/Evaluator.py", line 129, in run_triad
  File "/Path/MyProject/env/lib/python3.11/site-packages/trulens_eval/app.py", line 627, in wait_for_feedback_results
  File "/Path/MyProject/env/lib/python3.11/site-packages/trulens_eval/schema/record.py", line 186, in wait_for_feedback_results
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
  File "/Path/MyProject/env/lib/python3.11/site-packages/trulens_eval/utils/python.py", line 475, in _future_target_wrapper
  File "/Path/MyProject/env/lib/python3.11/site-packages/trulens_eval/utils/threading.py", line 168, in _run_with_timeout
  File "/Path/MyProject/env/lib/python3.11/site-packages/trulens_eval/utils/threading.py", line 159, in _run_with_timeout
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 458, in result
TimeoutError
```
(App continues to run after this error, but freezes)

**Environment:**
 - OS: MacOS M3
 - Python Version 3.11
 - TruLens version 0.30.1

**Additional context**
Custom app being used

**Comment by sfc-gh-pmardziel** [comment]
Hi @cabouezzi , I just added some functionality to `App.wait_for_feedback_results` that might address this issue. There is now a default timeout. Check you can check it out before the next release by installing the branch in this PR: https://github.com/truera/trulens/pull/1267 .

**Comment by sfc-gh-jreini** [comment]
Closing for now @cabouezzi - let me know if this isn't resolved.
