### ISSUE TITLE
[BUG] Mistyped variable names in DB.delete_app function in sqlalchemy.py

### ISSUE THREAD

**Issue by rishwanth-thiyagaraj** [truera/trulens#1320]
**Bug Description**
Using tru.delete_app(app_id) throws an error because of mistyped variable names.

**To Reproduce**
- Create Tru database with default settings.
- Create an app with an app_id.
- Try deleting it with delete_app functionality of Tru class.

**Expected behavior**
- The app and its' records deleted from the database of Trulens.

**Relevant Logs/Tracebacks**
Traceback (most recent call last):
  File "D:\Tetris\server\trulens_middleware\reset_database.py", line 6, in <module>
    tru.delete_app(app_id=os.getenv("TRULENS_APP_ID"))
  File "D:\Tetris\server\.venv\Lib\site-packages\trulens_eval\tru.py", line 565, in delete_app
    self.db.delete_app(app_id=app_id)
  File "D:\Tetris\server\.venv\Lib\site-packages\trulens_eval\database\sqlalchemy.py", line 373, in delete_app
    with self.Session.begin() as session:
         ^^^^^^^^^^^^
  File "D:\Tetris\server\.venv\Lib\site-packages\pydantic\main.py", line 828, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'SQLAlchemyDB' object has no attribute 'Session'. Did you mean: 'session'?

**Environment:**
 - OS: [Windows]
 - Python Version - 3.11.7
 - TruLens version - 0.33.0

**Additional context**

**Comment by rishwanth-thiyagaraj** [comment]
@dosu how can I get permission to push changes to this github repo
