### ISSUE TITLE
[BUG] Langchain using chain.stream could not shown result on trulens dashboard

### ISSUE THREAD

**Issue by zongyicoding** [truera/trulens#1357]
**Bug Description**
I am currently using langchain's chain.stream to batch output results to the frontend web page. After the output ends, I cannot correctly capture the output and scores of LLM (there is no data at all on the Dashboard). How can I correctly wait for the LLM output to be completed and then record the complete output in the Trulens dashboard and give the correct score?

**To Reproduce**
```python
from fastapi import FastAPI
from fastapi.responses import StreamingResponse, FileResponse
from langchain_openai import ChatOpenAI
from langchain.schema import Document
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores.chroma import Chroma
from langchain_core.runnables import RunnablePassthrough
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from trulens_eval import TruChain, Feedback
from trulens_eval.feedback.provider import OpenAI

from trulens_eval import Tru

tru = Tru()
tru.run_dashboard(port=9999, force=True)

embedding_function = OpenAIEmbeddings(
            model="text-embedding-ada-002",
            check_embedding_ctx_length=False)

docs = [
    Document(
        page_content="the dog loves to eat pizza", metadata={"source": "animal.txt"}
    ),
    Document(
        page_content="the cat loves to eat lasagna", metadata={"source": "animal.txt"}
    ),
]

db = Chroma.from_documents(docs, embedding_function)
retriever = db.as_retriever()


template = """Answer the question based only on the following context:
{context}

Question: {question}
"""
prompt = ChatPromptTemplate.from_template(template)
model = ChatOpenAI(temperature=0,
                   streaming=True, 
                   model='gpt-3.5')

provider = OpenAI()
retrieval_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | model
    | StrOutputParser()
)

f_answer_relevance = (
    Feedback(provider.context_relevance_with_cot_reasons, name = "Answer Relevance")
    .on_input_output()
)

tru_recorder = TruChain(retrieval_chain,
    app_id='conversation_stream',
    feedbacks=[f_answer_relevance],
    )

app = FastAPI()

async def generate_chat_responses(message):
    with tru_recorder:
        for chunk in retrieval_chain.stream(message):
            content = chunk.replace("\n", "<br>")
            print(f'content: {content}')
            yield f"data: {content}\n\n"

@app.get("/")
async def root():
    return FileResponse("static/index.html")

@app.get("/chat_stream/{message}")
async def chat_stream(message: str):
    return StreamingResponse(generate_chat_responses(message=message), media_type="text/event-stream")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="127.0.0.1", port=8000)

``` 
**Expected behavior**
The following two behaviors are both acceptable. 
- Complete the waiting for the generation results of the streaming and record the complete information in the Dashboard.

- After the LLM generation is completed, provide the response to Trulens for analysis and save it to the dashboard.

**Environment:**

- OS: [e.g. MacOS, Windows] MacOS 14.5
- Python Version 3.12
- TruLens version 0.33.0
- Versions of other relevant installed libraries

**Additional context**

**Comment by zongyicoding** [comment]
hi @sfc-gh-srudenko 
After modifying the code, I encountered two issues. 
1. In my case, I used the api_key and base_url provided by the company. When I used OpenAI embedding, I couldn't invoke Trulens properly. The error message is as follows:
```
Exception has occurred: Exception
Feedback function FeedbackDefinition(Answer Relevance,
	selectors={'question': Lens().__record__.main_input, 'context': Lens().__record__.main_output},
	if_exists=None
) is not loadable. Cannot use DEFERRED feedback mode. The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

The above exception was the direct cause of the following exception:

  File "/Applications/FastAPI-LangChain-Streaming-main/new_app.py", line 66, in <module>
    tru_recorder = TruChain(
                   ^^^^^^^^^
Exception: Feedback function FeedbackDefinition(Answer Relevance,
	selectors={'question': Lens().__record__.main_input, 'context': Lens().__record__.main_output},
	if_exists=None
) is not loadable. Cannot use DEFERRED feedback mode. The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
``` 
2. When I use my own private OPENAI_API_KEY, another error message pops up.
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/responses.py", line 265, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/responses.py", line 238, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 555, in receive
    await self.message_event.wait()
  File "/opt/anaconda3/envs/delete_env/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
  File "/opt/anaconda3/envs/delete_env/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/opt/anaconda3/envs/delete_env/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/opt/anaconda3/envs/delete_env/lib/python3.11/asyncio/futures.py", line 198, in result
    raise exc
asyncio.exceptions.CancelledError: Cancelled by cancel scope 31e318690

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/routing.py", line 754, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/routing.py", line 774, in app
  |     await route.handle(scope, receive, send)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/routing.py", line 295, in handle
  |     await self.app(scope, receive, send)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/responses.py", line 258, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/asyncio/tasks.py", line 277, in __step
    |     result = coro.send(None)
    |              ^^^^^^^^^^^^^^^
    |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    |     await func()
    |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/Applications/FastAPI-LangChain-Streaming-main/new_app.py", line 78, in generate_chat_responses
    |     with tru_recorder as recording:
    |   File "/opt/anaconda3/envs/delete_env/lib/python3.11/site-packages/trulens_eval/app.py", line 1063, in __exit__
    |     raise exc_value
    |   File "/Applications/FastAPI-LangChain-Streaming-main/new_app.py", line 80, in generate_chat_responses
    |     retrieval_chain.acall(
    |     ^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: 'RunnableSequence' object has no attribute 'acall'
    +------------------------------------
``` 
In my experimental environment, I need to use internal api_key and base_url. Is there any way to solve this problem?

**Comment by zongyicoding** [comment]
Hi @sfc-gh-jreini, 
After following dosu's suggestion, I am now able to retrieve data on the dashboard. However, the results still have some issues: 
1. The answers that were previously retrievable from the stream loop are no longer accessible. 
2. The dashboard is storing four records for a single question, but none of these records contain the actual answer. Below is the corrected code. 
note: my langchain version is 0.2.x, the acall method has been changed to ainvoke.
```python
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse, FileResponse
from langchain_openai import ChatOpenAI
from langchain.schema import Document
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores.chroma import Chroma
from langchain_core.runnables import RunnablePassthrough
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from trulens_eval import TruChain, Feedback
from trulens_eval.feedback.provider import OpenAI
from trulens_eval import Tru
from langchain.callbacks import AsyncIteratorCallbackHandler
import asyncio
import os 
from dotenv import load_dotenv
load_dotenv()

tru = Tru()
tru.reset_database()
tru.run_dashboard(port=9999, force=True)

embedding_function = OpenAIEmbeddings(
    model="text-embedding-ada-002",
    check_embedding_ctx_length=False,
    api_key=os.environ['API_KEY']
)

docs = [
    Document(
        page_content="the dog loves to eat pizza", metadata={"source": "animal.txt"}
    ),
    Document(
        page_content="the cat loves to eat lasagna", metadata={"source": "animal.txt"}
    ),
]

db = Chroma.from_documents(docs, embedding_function)
retriever = db.as_retriever()

template = """Answer the question based only on the following context:
{context}

Question: {question}
"""
prompt = ChatPromptTemplate.from_template(template)
model = ChatOpenAI(temperature=0, streaming=True, api_key=os.environ['API_KEY'],model='gpt-3.5')

provider = OpenAI(api_key=os.environ['API_KEY'])
retrieval_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | model
    | StrOutputParser()
)

f_answer_relevance = (
    Feedback(provider.context_relevance_with_cot_reasons, name="Answer Relevance")
    .on_input_output()
)

tru_recorder = TruChain(
    retrieval_chain,
    app_id='conversation_stream',
    feedbacks=[f_answer_relevance],
    feedback_mode="deferred"
)

app = FastAPI()

async def generate_chat_responses(message):
    callback = AsyncIteratorCallbackHandler()
    
    with tru_recorder as recording:
        task = asyncio.create_task(
            retrieval_chain.ainvoke(

                input=dict(question=message),
                callbacks=[callback]
            )
        )
    
    response = ""
    async for token in callback.aiter():
        content = token.replace("\n", "<br>")
        print(f'content: {content}')
        response += content
        yield f"data: {content}\n\n"
    
    await task
    record = recording.get()
    print(f'Record: {record}')

@app.get("/")
async def root():
    return FileResponse("static/index.html")

@app.get("/chat_stream/{message}")
async def chat_stream(message: str):
    return StreamingResponse(generate_chat_responses(message=message), media_type="text/event-stream")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8080)
``` 

```
WARNI [chromadb.segment.impl.vector.local_hnsw] Number of requested results 4 is greater than number of elements in index 2, updating n_results = 2
WARNI [trulens_eval.app] Unsure what the main input string is for the call to _aget_relevant_documents with args [{'question': 'what is 1+2 = ? explain it please !'}, <langchain_core.callbacks.manager.AsyncCallbackManagerForRetrieverRun object at 0x169c06610>].
WARNI [trulens_eval.app] Focus {'question': 'what is 1+2 = ? explain it please !'} is not a sequence.
WARNI [trulens_eval.app] Could not determine main input/output of [{'question': 'what is 1+2 = ? explain it please !'}, <langchain_core.callbacks.manager.AsyncCallbackManagerForRetrieverRun object at 0x169c06610>].
WARNI [trulens_eval.app] Could not determine main output from messages=[HumanMessage(content="Answer the question based only on the following context:\n[Document(metadata={'source': 'animal.txt'}, page_content='the dog loves to eat pizza'), Document(metadata={'source': 'animal.txt'}, page_content='the cat loves to eat lasagna')]\n\nQuestion: {'question': 'what is 1+2 = ? explain it please !'}\n")].
``` 
 Please assist in addressing these issues. Thank you.

**Comment by sfc-gh-jreini** [comment]
We have a fixes coming for async and streaming in [this PR](https://github.com/truera/trulens/pull/1441).

Feel free to install it from the branch if you'd like to try it now, otherwise we'll have it in the next release.
