### ISSUE TITLE
Evaluate local deployment finetuned LLM, LLM of openai interface as feedback provider, RunTimeError occurred

### ISSUE THREAD

**Issue by 2500035435** [truera/trulens#1486]
```
from langchain_openai import ChatOpenAI
import pandas as pd

glm4_base_client = ChatOpenAI(model="glm-4v-9b",
                          api_key="your_api_key",
                          base_url="http://0.0.0.0:8000/v1/",
                          )
glm4_finetune_client = ChatOpenAI(model="glm-4v-9b",
                          api_key="your_api_key",
                          base_url="http://0.0.0.0:8001/v1/",
                          )

test_dataset = pd.read_csv("test_output.csv")
test_dataset.rename(columns={"Input": "query", "GT Response": "response"}, inplace=True)
golden_set = test_dataset[["query", "response"]].to_dict(orient="records")

feedback_provider = OpenAI(
                           model_engine="qwen-max",
                           endpoint="https://dashscope.aliyuncs.com/compatible-mode/v1",
                           api_key="******",
                           )

ground_truth = GroundTruthAgreement(golden_set, provider=feedback_provider)

f_groundtruth = (
    Feedback(ground_truth.agreement_measure, name="Ground Truth Agreement")
    .on_input_output()
)

f_answer_relevance = (
    Feedback(feedback_provider.relevance_with_cot_reasons, name="Answer Relevance")
    .on_input_output()
)

def base_model(query):
    response = glm4_base_client.invoke(query).content
    return response

def finetuned_model(query):
    response = glm4_finetune_client.invoke(query).content
    return response

base_recorder = TruBasicApp(
    base_model,
    app_name="LLM",
    app_version="base",
    feedbacks=[
        f_groundtruth,
        f_answer_relevance,
    ],
)

finetuned_recorder = TruBasicApp(
    finetuned_model,
    app_name="LLM",
    app_version="finetuned",
    feedbacks=[
        f_groundtruth,
        f_answer_relevance,
    ],
)

for i in range(len(test_dataset)):
    with base_recorder as recording:
        base_recorder.app(test_dataset["query"][i])

    with finetuned_recorder as recording:
        finetuned_recorder.app(test_dataset["query"][i])
```

ERROR AS FOLLOWS:
```
Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
Feedback Function exception caught: Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/feedback.py", line 895, in run
    mod_base_endpoint.Endpoint.track_all_costs_tally(
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 524, in track_all_costs_tally
    result, cbs = Endpoint.track_all_costs(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 504, in track_all_costs
    return Endpoint._track_costs(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 601, in _track_costs
    result: T = __func(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/feedback/groundtruth.py", line 223, in agreement_measure
    ground_truth_response = self._find_response(prompt)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/feedback/groundtruth.py", line 161, in _find_response
    responses = [
                ^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/feedback/groundtruth.py", line 162, in <listcomp>
    qr["expected_response"]
    ~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'expected_response'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/feedback.py", line 910, in run
    raise RuntimeError(
RuntimeError: Evaluation of Ground Truth Agreement failed on inputs: 
{'prompt': '波纹黄尺蛾在广西南宁一带哪个时期发生数量较多？',
 'response': '波纹黄尺蛾在广西南宁一带通常在春季和夏季的温暖季节发生数量较多。具体来说，主要集中在4月至6月期间，这段时间内气候适宜，有利于其繁殖和活动。'}.

```
I try to use local deployment llm (base and finetuned), feedback provider use openai llm with endpoint and api_key, and evaluate in my dataset. 

I want to know how to make sure that the feedback provider can be called normally, and how to fix the error with my part of the code causing an error(reference [)](https://github.com/truera/trulens/blob/main/examples/expositional/models/bedrock/bedrock_finetuning_experiments.ipynb) to build my code. 

Any helpful help would be greatly appreciated.

**Comment by 2500035435** [comment]
@dosu 
OK, I followed your advice, add `test_dataset["expected_response"] = None` and `golden_set = test_dataset[["query", "response", "expected_response"]].to_dict(orient="records")`. But no other code changes were suggested because the code I provided did not include the part of the code you mentioned
```
test_dataset = pd.read_csv("test_output.csv")
test_dataset.rename(columns={"Input": "query", "GT Response": "response"}, inplace=True)
test_dataset["expected_response"] = None  # Add this line to include the expected_response key
golden_set = test_dataset[["query", "response", "expected_response"]].to_dict(orient="records")
```
```
Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=3.
Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=3.
Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=2.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=3.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=2.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=3.
Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=1.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=2.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=1.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=2.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=3.
Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=1.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=0.
Feedback Function exception caught: Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/feedback.py", line 895, in run
    mod_base_endpoint.Endpoint.track_all_costs_tally(
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 524, in track_all_costs_tally
    result, cbs = Endpoint.track_all_costs(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 504, in track_all_costs
    return Endpoint._track_costs(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 601, in _track_costs
    result: T = __func(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/feedback/llm_provider.py", line 565, in relevance_with_cot_reasons
    return self.generate_score_and_reasons(system_prompt, user_prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/feedback/llm_provider.py", line 218, in generate_score_and_reasons
    response = self.endpoint.run_in_pace(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 323, in run_in_pace
    raise RuntimeError(
RuntimeError: Endpoint openai request failed 4 time(s): 
	Connection error.
	Connection error.
	Connection error.
	Connection error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/feedback.py", line 910, in run
    raise RuntimeError(
RuntimeError: Evaluation of Answer Relevance failed on inputs: 
{'prompt': '为什么需要促使新梢抽发整齐健壮？',
 'response': '促使新梢抽发整齐健壮对于果树生长和产量有重要意义，具体原因如下：\n'
             '\n'
             '1. **均匀光照**：整齐的.

Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=2.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=1.
openai request failed <class 'openai.APIConnectionError'>=Connection error.. Retries remaining=0.
Feedback Function exception caught: Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/feedback.py", line 895, in run
    mod_base_endpoint.Endpoint.track_all_costs_tally(
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 524, in track_all_costs_tally
    result, cbs = Endpoint.track_all_costs(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 504, in track_all_costs
    return Endpoint._track_costs(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 601, in _track_costs
    result: T = __func(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/feedback/llm_provider.py", line 565, in relevance_with_cot_reasons
    return self.generate_score_and_reasons(system_prompt, user_prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/feedback/llm_provider.py", line 218, in generate_score_and_reasons
    response = self.endpoint.run_in_pace(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/endpoint.py", line 323, in run_in_pace
    raise RuntimeError(
RuntimeError: Endpoint openai request failed 4 time(s): 
	Connection error.
	Connection error.
	Connection error.
	Connection error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/trulens/core/feedback/feedback.py", line 910, in run
    raise RuntimeError(
RuntimeError: Evaluation of Answer Relevance failed on inputs: 
{'prompt': '蠹虫主要危害荔枝的哪个部位？',
 'response': '**1. 荔枝嫩梢**\n'
             '蠹虫主要以荔枝树的嫩梢为食，它们会咬食嫩梢的顶端部分，导致新梢生长受阻。\n'
             '\n.

Callback class OpenAICallback is registered for handling create but there are no endpoints waiting to receive the result.
```
but now the ERROR are reported as above. How can I fix it?

**Comment by 2500035435** [comment]
@dosu
If I use 
```
from trulens.providers.openai.provider import OpenAI
openai_provider = OpenAI()
```
How do I set it up model_name, base_url and apy_key to call the llm?

**Comment by 2500035435** [comment]
@ dosu
Now I pass parameters when iitializing OpenAI class. Test sample as follow:
```
from trulens.providers.openai import OpenAI
feedback_provider = OpenAI(
                           model_engine="glm-4v-9b",
                           endpoint="http://0.0.0.0:8000/v1/",
                           api_key="your_api_key",
                           )
```
I use the local deployment llm, "http://0.0.0.0:8000/v1/"  is what I published through api server. 
Which code methods should I call to test whether feedback_provider can call my locally deployed llm?

**Comment by 2500035435** [comment]
@dosu
Now I pass parameters when iitializing OpenAI class. Test sample as follow:
```
from trulens.providers.openai import OpenAI
feedback_provider = OpenAI(
                           model_engine="glm-4v-9b",
                           endpoint="http://0.0.0.0:8000/v1/",
                           api_key="your_api_key",
                           )
```
I use the local deployment llm, "http://0.0.0.0:8000/v1/"  is what I published through api server. 
Which code methods should I call to test whether feedback_provider can call my locally deployed llm?

**Comment by 2500035435** [comment]
@dosu
```
from trulens.providers.openai import OpenAI
feedback_provider = OpenAI(
                           model_engine="glm-4v-9b",
                           endpoint="http://0.0.0.0:8000/v1/",
                           api_key="your_api_key",
                           )
```
Can you test whether feedback_provider works on my code base？

**Comment by 2500035435** [comment]
@dosu
thank you for the test code:
from trulens.providers.openai import OpenAI

```
# Initialize the feedback provider
feedback_provider = OpenAI(
    model_engine="glm-4v-9b",
    endpoint="http://0.0.0.0:8000/v1/",
    api_key="your_api_key",
)

# Example usage: create a chat completion
try:
    response = feedback_provider._create_chat_completion(prompt="Hello, how are you?")
    print("Chat completion response:", response)
except Exception as e:
    print("Error:", e)
```
unfortunatlly, it return `Error: Connection error.`
I think its not my lllm's problem, beceuse when I run:
```
from langchain_openai import ChatOpenAI

glm4_base_client = ChatOpenAI(model="glm-4v-9b",
                          api_key="your_api_key",
                          base_url="http://0.0.0.0:8000/v1/",
                          )
glm4_base_client.invoke("hello")
```
llm can respond normally. What do you think?

**Comment by 2500035435** [comment]
@dosu
I took your advice, use logging to find out problem:
```
import logging
from trulens.providers.openai import OpenAI

# Configure logging
logging.basicConfig(level=logging.DEBUG)

# Initialize the feedback provider
feedback_provider = OpenAI(
    model_engine="glm-4v-9b",
    endpoint="http://0.0.0.0:8000/v1/",
    api_key="your_api_key",
)

# Example usage: create a chat completion
try:
    response = feedback_provider._create_chat_completion(prompt="Hello, how are you?")
    print("Chat completion response:", response)
except Exception as e:
    logging.error("Error: %s", e)
```
The DEBUG as follows:
```
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/usr/lib/ssl/certs/ca-certificates.crt'
DEBUG:trulens.core.feedback.endpoint:module <module 'openai.resources' from '/root/anaconda3/envs/trulens/lib/python3.11/site-packages/openai/resources/__init__.py'> already instrumented for create
DEBUG:trulens.core.feedback.endpoint:module <module 'openai.resources.chat' from '/root/anaconda3/envs/trulens/lib/python3.11/site-packages/openai/resources/chat/__init__.py'> already instrumented for create
DEBUG:trulens.core.feedback.endpoint:Calling instrumented method <function Completions.create at 0x7ff21ddbf420> of type <class 'function'>, iscoroutinefunction=False, isasyncgeneratorfunction=False
DEBUG:openai._base_client:Request options: {'method': 'post', 'url': '/chat/completions', 'files': None, 'json_data': {'messages': [{'role': 'system', 'content': 'Hello, how are you?'}], 'model': 'glm-4v-9b', 'seed': 123, 'temperature': 0.0}}
DEBUG:openai._base_client:Sending HTTP Request: POST https://api.openai.com/v1/chat/completions
DEBUG:httpcore.connection:connect_tcp.started host='api.openai.com' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.failed exception=ConnectError(OSError(101, 'Network is unreachable'))
DEBUG:openai._base_client:Encountered Exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/root/anaconda3/envs/trulens/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/root/anaconda3/envs/trulens/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 101] Network is unreachable
DEBUG:openai._base_client:1 retry left
INFO:openai._base_client:Retrying request to /chat/completions in 0.967390 seconds
DEBUG:openai._base_client:Request options: {'method': 'post', 'url': '/chat/completions', 'files': None, 'json_data': {'messages': [{'role': 'system', 'content': 'Hello, how are you?'}], 'model': 'glm-4v-9b', 'seed': 123, 'temperature': 0.0}}
DEBUG:openai._base_client:Sending HTTP Request: POST https://api.openai.com/v1/chat/completions
DEBUG:httpcore.connection:connect_tcp.started host='api.openai.com' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.failed exception=ConnectError(OSError(101, 'Network is unreachable'))
DEBUG:openai._base_client:Encountered Exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/root/anaconda3/envs/trulens/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/root/anaconda3/envs/trulens/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 101] Network is unreachable
DEBUG:openai._base_client:0 retries left
INFO:openai._base_client:Retrying request to /chat/completions in 1.826524 seconds
DEBUG:openai._base_client:Request options: {'method': 'post', 'url': '/chat/completions', 'files': None, 'json_data': {'messages': [{'role': 'system', 'content': 'Hello, how are you?'}], 'model': 'glm-4v-9b', 'seed': 123, 'temperature': 0.0}}
DEBUG:openai._base_client:Sending HTTP Request: POST https://api.openai.com/v1/chat/completions
DEBUG:httpcore.connection:connect_tcp.started host='api.openai.com' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.failed exception=ConnectError(OSError(101, 'Network is unreachable'))
DEBUG:openai._base_client:Encountered Exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/root/anaconda3/envs/trulens/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/openai/_base_client.py", line 973, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/root/anaconda3/envs/trulens/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/trulens/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 101] Network is unreachable
DEBUG:openai._base_client:Raising connection error
ERROR:root:Error: Connection error.
```
It's that means the code cannot connect to the server? By the way, the llm glm-4v-9b was deployment on my server, connection failure is not possible, the test code prove that.
```
from langchain_openai import ChatOpenAI

glm4_base_client = ChatOpenAI(model="glm-4v-9b",
                          api_key="your_api_key",
                          base_url="http://0.0.0.0:8000/v1/",
                          )
glm4_base_client.invoke("hello")
```

**Comment by sfc-gh-chu** [comment]
@2500035435 to confirm, are you using an Azure OpenAI deployment? If so you can try

```python
from trulens.providers.openai.provider import AzureOpenAI

feedback_provider = AzureOpenAI(
    deployment_name="glm-4v-9b",
    azure_endpoint="http://0.0.0.0:8000/v1/",
    api_key="your_api_key",
    api_version="api_version" # optionally
)
```

You can find an [example](https://www.trulens.org/examples/models/azure/azure_openai_langchain/#import-from-trulens) and [API reference](https://www.trulens.org/reference/trulens/providers/openai/provider/#trulens.providers.openai.provider.AzureOpenAI)

**Comment by sfc-gh-chu** [comment]
To use an OpenAI provider with a different base URL, you can run

```python
from trulens.providers.openai.provider import OpenAI

feedback_provider = OpenAI(
    model_engine="glm-4v-9b",
    base_url="http://0.0.0.0:8000/v1/",
    api_key="your_api_key"
)
```
