### ISSUE TITLE
Testing Local LLMs?

### ISSUE THREAD

**Issue by abhishekrai43** [truera/trulens#297]
```
import os
from langchain import PromptTemplate, LLMChain
from langchain.llms import GPT4All
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.vectorstores.faiss import FAISS
from langchain.embeddings import HuggingFaceEmbeddings
from trulens_eval import TruChain, Feedback, Huggingface, Tru


tru = Tru()


os.environ["HUGGINGFACE_API_KEY"] = ""


gpt4all_path = './models/gpt4all-converted.bin'


callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])


embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')
hugs = Huggingface()


f_lang_match = Feedback(hugs.language_match).on_input_output()

llm = GPT4All(model=gpt4all_path,verbose=True,temp=0.2)


index = FAISS.load_local("my_faiss_index", embeddings)


template = """Answer the following question using {context}
Question: {question}
Answer:
"""


def get_best_answer(question):
    matched_docs, sources = similarity_search(question, index, n=4)
    context = "\n".join([doc.page_content for doc in matched_docs])
    prompt = PromptTemplate(template=template, input_variables=["context", "question"]).partial(context=context)
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    truchain = TruChain(llm_chain, app_id='Chain1_ChatApplication', feedbacks=[f_lang_match],tags = "prototype")
    answer = truchain.run(question)
    return answer



def similarity_search(query, index, n=4):
    matched_docs = index.similarity_search(query, k=n)
    sources = []
    for doc in matched_docs:
        sources.append(
            {
                "page_content": doc.page_content,
                "metadata": doc.metadata,
            }
        )
    return matched_docs, sources


while True:

    question = input("Please enter your question (or type 'exit' to close the program): ")


    if question.lower() == "exit":
        break


    answer = get_best_answer(question)


    print("Answer:", answer)

```
gives

```
✅ app Chain1_ChatApplication -> default.sqlite
✅ feedback def. feedback_definition_hash_44c43fe23fdbb98055154e6bb126142a -> default.sqlite
Traceback (most recent call last):
  File "c:\Users\abhishek\Local-LLM\gpt4all_truelens.py", line 75, in <module>
    answer = get_best_answer(question)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\abhishek\Local-LLM\gpt4all_truelens.py", line 48, in get_best_answer
    answer = truchain.run(question)
             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'RuntimeError' object is not callable`

```

**Comment by rshih32** [comment]
Can you try taking out the `.run` call? The TruChain should be called via `truchain(question)`

**Comment by abhishekrai43** [comment]
Thanks it works

**Comment by abhishekrai43** [comment]
Thanks, It works using above.
