### ISSUE TITLE
AzureOpenAI fails: missing deployment_id 

### ISSUE THREAD

**Issue by Mymoza** [truera/trulens#337]
Bug when using the new AzureOpenAI wrapper added in PR #242 

### How to reproduce: 
```
azure = AzureOpenAI(model_engine="gpt-35-turbo", deployment_id="gpt-4")
```

### Error: 
```
Traceback (most recent call last):
  File "/home/lab/lab392-rfpvirtualassistant/scripts/langchain/eval.py", line 15, in <module>
    pipeline = QAPipeline(config['AWS']['AWSKendraSearchIndexId'], config['OpenAI']['OpenAIAnswerDeployment'], eval_mode=True, answers=answers)
  File "/home/lab/lab392-rfpvirtualassistant/scripts/langchain/pipeline.py", line 58, in __init__
    azure = AzureOpenAI(model_engine="gpt-35-turbo", deployment_id=openAIDeployment)
  File "/home/lab/anaconda/envs/lab392/lib/python3.10/site-packages/trulens_eval/feedback.py", line 1689, in __init__
    super().__init__(
  File "/home/lab/anaconda/envs/lab392/lib/python3.10/site-packages/trulens_eval/feedback.py", line 1049, in __init__
    super().__init__(
  File "/home/lab/anaconda/envs/lab392/lib/python3.10/site-packages/trulens_eval/feedback.py", line 1020, in __init__
    super().__init__(*args, **kwargs)
  File "/home/lab/anaconda/envs/lab392/lib/python3.10/site-packages/trulens_eval/util.py", line 1660, in __init__
    super().__init__(__tru_class_info=class_info, **kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AzureOpenAI
deployment_id
  field required (type=value_error.missing)
```

I believe the problem is that in class `OpenAI`, the `deployment_id` parameter is lost since it is not assigned to `self_kwargs`. PR incoming with my suggestion to fix this bug.

**Comment by Mymoza** [comment]
Fixed in #338
