### ISSUE TITLE
RuntimeError: Could not locate app.query.rets.source_nodes[:].note.text in app/record.

### ISSUE THREAD

**Issue by JIAWENee** [truera/trulens#944]
I'm trying to run trulens to evaluate the RAG triplet metric on my llama_index RAG.

My code:
```
from trulens_eval import TruLlama
from trulens_eval import FeedbackMode

tru_recoder = TruLlama(
    query_engine,
    app_id="App_1",
    feedbacks=[
        f_qa_relevance,
        f_qs_relevance,
        f_groundedness
    ]
)

with tru_recoder as recoding:
    query_engine.query("what are the key to building a career in AI?")
```

Error message:
```
Run of run in <Thread(TP.submit with debug timeout_0, started 10360)> failed with: Could not locate app.query.rets.source_nodes[:].note.text in app/record.
exception calling callback for <Future at 0x24b5f5873d0 state=finished raised RuntimeError>
Traceback (most recent call last):
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\feedback\feedback.py", line 708, in extract_selection
    arg_vals[k] = list(q_within_o.get(o))
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\utils\serial.py", line 943, in get
    for start_selection in start_items:
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\utils\serial.py", line 944, in get
    for last_selection in last_step.get(start_selection):
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\utils\serial.py", line 402, in get
    raise KeyError(
KeyError: 'Key not in dictionary: note'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\anaconda3\envs\torch_py310\lib\concurrent\futures\_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\app.py", line 1168, in _add_future_feedback
    res = future_result.result()
  File "D:\software\anaconda3\envs\torch_py310\lib\concurrent\futures\_base.py", line 451, in result
  return self.__get_result()
  File "D:\software\anaconda3\envs\torch_py310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\software\anaconda3\envs\torch_py310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\utils\python.py", line 374, in _future_target_wrapper
    return func(*args, **kwargs)
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\utils\threading.py", line 174, in _run_with_timeout
    raise e
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\utils\threading.py", line 159, in _run_with_timeout
    res: T = fut.result(timeout=timeout)
  File "D:\software\anaconda3\envs\torch_py310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "D:\software\anaconda3\envs\torch_py310\lib\concurrent\futures\_base.py", line 403, in __get_result
  raise self._exception
  File "D:\software\anaconda3\envs\torch_py310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\feedback\feedback.py", line 504, in run
    raise e
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\feedback\feedback.py", line 499, in run
    input_combinations = list(
  File "D:\software\anaconda3\envs\torch_py310\lib\site-packages\trulens_eval\feedback\feedback.py", line 710, in extract_selection
    raise RuntimeError(
RuntimeError: Could not locate app.query.rets.source_nodes[:].note.text in app/record.
```

**Comment by JIAWENee** [comment]
The RAG successfully runs the query but the metrics do not get computed. Any suggestions on how to fix?

**Comment by avinashmaheshjoshi** [comment]
Hey,

Could you please give a contained reproducible example to help with debugging.

**Comment by yuvneshtruera** [comment]
@JIAWENee Can you please give us an example to debug?

**Comment by oliverproudfoot** [comment]
```
from trulens_eval import Tru
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
from trulens_eval.feedback.provider import OpenAI
from trulens_eval import Feedback
import numpy as np
from trulens_eval.app import App
from trulens_eval.feedback import Groundedness
from trulens_eval import TruLlama

# Initialize provider class
tru = Tru(database_url=DATABASE_URL)
provider = OpenAI()

documents = SimpleDirectoryReader("data").load_data()
index = VectorStoreIndex.from_documents(documents)

query_engine = index.as_query_engine()

context = App.select_context(query_engine)

grounded = Groundedness(groundedness_provider=OpenAI())
# Define a groundedness feedback function
f_groundedness = (
    Feedback(grounded.groundedness_measure_with_cot_reasons)
    .on(context.collect())  # collect context chunks into a list
    .on_output()
    .aggregate(grounded.grounded_statements_aggregator)
)

# Question/answer relevance between overall question and answer.
f_answer_relevance = Feedback(provider.relevance).on_input_output()

# Question/statement relevance between question and each context chunk.
f_context_relevance = (
    Feedback(provider.context_relevance_with_cot_reasons)
    .on_input()
    .on(context)
    .aggregate(np.mean)
)

tru_query_engine_recorder = TruLlama(
    query_engine,
    app_id="LlamaIndex_App1",
    feedbacks=[f_groundedness, f_answer_relevance, f_context_relevance],
)

with tru_query_engine_recorder:
    res = await query_engine.aquery("What is the author's name?")
```

I get the same error when I run this.

**Comment by oliverproudfoot** [comment]
```
>>> trulens_eval.__version
0.27.2
>>> llama_index.core.__version__
0.10.30
```

**Comment by piotrm0** [comment]
Hi, can you try this alternative to set context:
```python
from trulens_eval import Select
context = Select.RecordCalls.ainvoke.rets.source_nodes[:]
```

The issue maybe our assumption that the main app method is `invoke` but you are using `ainvoke`.

**Comment by piotrm0** [comment]
> The RAG successfully runs the query but the metrics do not get computed. Any suggestions on how to fix?

Hi @JIAWENee , can you include the code that sets up the feedback functions you used?

**Comment by Sudhakar17** [comment]
@JIAWENee :  I am facing the same issues. did you fix this error? If yes, How?
